/**
 * Builds the host executable: the game server with the client embedded, as one file that
 * runs without Node or anything else installed. Needs Bun and a built client
 * (`npm run build`).
 *
 *   tsx server/scripts/build-host.ts [--target linux-x64,windows-x64,...|all]
 *
 * Without --target it builds for this computer. Files land in release/.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const dist = join(root, 'client/dist');
const buildDir = join(root, 'server/build');
const outDir = join(root, 'release');

/** Our names for the platforms, and Bun's. */
const TARGETS: Record<string, string> = {
  'windows-x64': 'bun-windows-x64',
  'linux-x64': 'bun-linux-x64',
  'linux-arm64': 'bun-linux-arm64',
  'macos-x64': 'bun-darwin-x64',
  'macos-arm64': 'bun-darwin-arm64',
};

const here = `${process.platform === 'win32' ? 'windows' : process.platform === 'darwin' ? 'macos' : 'linux'}-${process.arch}`;
const arg = process.argv.find((a, i) => process.argv[i - 1] === '--target');
const targets = !arg ? [here] : arg === 'all' ? Object.keys(TARGETS) : arg.split(',');
for (const t of targets) if (!TARGETS[t]) throw new Error(`Unknown target ${t}`);
if (!existsSync(join(dist, 'index.html'))) {
  throw new Error('The client is not built: run `npm run build` first.');
}

// An entry point that embeds every file of the built client, byte for byte, and starts
// the host with them.
const files: string[] = [];
const walk = (dir: string) => {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path);
    else files.push(relative(dist, path).split('\\').join('/'));
  }
};
walk(dist);
mkdirSync(buildDir, { recursive: true });
const entry = join(buildDir, 'host-entry.ts');
const fromEntry = (p: string) => relative(buildDir, p).split('\\').join('/');
writeFileSync(
  entry,
  [
    '// Generated by server/scripts/build-host.ts. Do not edit.',
    ...files.map(
      (f, i) =>
        `import f${i} from ${JSON.stringify(fromEntry(join(dist, f)))} with { type: 'file' };`,
    ),
    `import { embeddedFiles } from ${JSON.stringify(fromEntry(join(root, 'server/src/files.ts')))};`,
    `import { runHost } from ${JSON.stringify(fromEntry(join(root, 'server/src/host.ts')))};`,
    '',
    'await runHost({',
    '  files: embeddedFiles({',
    ...files.map((f, i) => `    ${JSON.stringify(f)}: f${i},`),
    '  }),',
    '  https: true,',
    '  open: true,',
    '  pauseOnError: true,',
    '});',
    '',
  ].join('\n'),
);

mkdirSync(outDir, { recursive: true });
for (const t of targets) {
  const out = join(
    outDir,
    `some-assembly-required-host-${t}${t.startsWith('windows') ? '.exe' : ''}`,
  );
  console.log(`Building ${relative(root, out)} (${files.length} client files embedded)`);
  execFileSync(
    'bun',
    ['build', '--compile', '--minify', `--target=${TARGETS[t]}`, entry, '--outfile', out],
    { stdio: 'inherit', cwd: root },
  );
}
